name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@2.31.1
        with:
          php-version: 8.2

      - name: Install dependencies
        run: composer install

      - name: Run tests
        run: |
          sh run_tests.sh

      - name: Log in to DockerHub
        uses: docker/login-action@v3.3.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t php-app .
          docker tag php-app ${{ secrets.DOCKER_USERNAME }}/php-app:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/php-app:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build-push
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to ec2 instance
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          scirpt: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/php-app
            docker pull ${{ secrets.DOCKER_USERNAME }}/php-app

            docker-compose down
            docker-compose up -d --build
